version: '3.1'

networks:
   dev:

volumes:
  pg_nicelink:

services:
  nicelink_db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=nicelink
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=linker
    volumes:
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - '127.0.0.1:5432:5432'
    networks:
      - dev
  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - nicelink_db
    environment:
       SPRING_DATASOURCE_URL : 'jdbc:postgresql://nicelink_db:5432/nicelink'
       JAVA_OPTS : '-Xmx512m'
    networks:
      - dev
